/*
Hava

Hava API

API version: 1.1.3
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// EnvironmentsIndex200Response struct for EnvironmentsIndex200Response
type EnvironmentsIndex200Response struct {
	// The token to pass through to get the next page of results, if there are any.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// The total amount of results to be paginated
	TotalSize *int32 `json:"total_size,omitempty"`
	// The results for the current page
	Results []EnvironmentSummary `json:"results,omitempty"`
}

// NewEnvironmentsIndex200Response instantiates a new EnvironmentsIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentsIndex200Response() *EnvironmentsIndex200Response {
	this := EnvironmentsIndex200Response{}
	return &this
}

// NewEnvironmentsIndex200ResponseWithDefaults instantiates a new EnvironmentsIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentsIndex200ResponseWithDefaults() *EnvironmentsIndex200Response {
	this := EnvironmentsIndex200Response{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *EnvironmentsIndex200Response) GetNextPageToken() string {
	if o == nil || isNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsIndex200Response) GetNextPageTokenOk() (*string, bool) {
	if o == nil || isNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *EnvironmentsIndex200Response) HasNextPageToken() bool {
	if o != nil && !isNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *EnvironmentsIndex200Response) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetTotalSize returns the TotalSize field value if set, zero value otherwise.
func (o *EnvironmentsIndex200Response) GetTotalSize() int32 {
	if o == nil || isNil(o.TotalSize) {
		var ret int32
		return ret
	}
	return *o.TotalSize
}

// GetTotalSizeOk returns a tuple with the TotalSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsIndex200Response) GetTotalSizeOk() (*int32, bool) {
	if o == nil || isNil(o.TotalSize) {
		return nil, false
	}
	return o.TotalSize, true
}

// HasTotalSize returns a boolean if a field has been set.
func (o *EnvironmentsIndex200Response) HasTotalSize() bool {
	if o != nil && !isNil(o.TotalSize) {
		return true
	}

	return false
}

// SetTotalSize gets a reference to the given int32 and assigns it to the TotalSize field.
func (o *EnvironmentsIndex200Response) SetTotalSize(v int32) {
	o.TotalSize = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *EnvironmentsIndex200Response) GetResults() []EnvironmentSummary {
	if o == nil || isNil(o.Results) {
		var ret []EnvironmentSummary
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsIndex200Response) GetResultsOk() ([]EnvironmentSummary, bool) {
	if o == nil || isNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *EnvironmentsIndex200Response) HasResults() bool {
	if o != nil && !isNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []EnvironmentSummary and assigns it to the Results field.
func (o *EnvironmentsIndex200Response) SetResults(v []EnvironmentSummary) {
	o.Results = v
}

func (o EnvironmentsIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.NextPageToken) {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	if !isNil(o.TotalSize) {
		toSerialize["total_size"] = o.TotalSize
	}
	if !isNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentsIndex200Response struct {
	value *EnvironmentsIndex200Response
	isSet bool
}

func (v NullableEnvironmentsIndex200Response) Get() *EnvironmentsIndex200Response {
	return v.value
}

func (v *NullableEnvironmentsIndex200Response) Set(val *EnvironmentsIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentsIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentsIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentsIndex200Response(val *EnvironmentsIndex200Response) *NullableEnvironmentsIndex200Response {
	return &NullableEnvironmentsIndex200Response{value: val, isSet: true}
}

func (v NullableEnvironmentsIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentsIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
