/*
Hava

Hava API

API version: 1.1.2
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// ResourceTagsInner struct for ResourceTagsInner
type ResourceTagsInner struct {
	// The key of the tag
	Key *string `json:"key,omitempty"`
	// The value of the tag
	Value *string `json:"value,omitempty"`
}

// NewResourceTagsInner instantiates a new ResourceTagsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceTagsInner() *ResourceTagsInner {
	this := ResourceTagsInner{}
	return &this
}

// NewResourceTagsInnerWithDefaults instantiates a new ResourceTagsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceTagsInnerWithDefaults() *ResourceTagsInner {
	this := ResourceTagsInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ResourceTagsInner) GetKey() string {
	if o == nil || isNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTagsInner) GetKeyOk() (*string, bool) {
	if o == nil || isNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ResourceTagsInner) HasKey() bool {
	if o != nil && !isNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ResourceTagsInner) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ResourceTagsInner) GetValue() string {
	if o == nil || isNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTagsInner) GetValueOk() (*string, bool) {
	if o == nil || isNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResourceTagsInner) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ResourceTagsInner) SetValue(v string) {
	o.Value = &v
}

func (o ResourceTagsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableResourceTagsInner struct {
	value *ResourceTagsInner
	isSet bool
}

func (v NullableResourceTagsInner) Get() *ResourceTagsInner {
	return v.value
}

func (v *NullableResourceTagsInner) Set(val *ResourceTagsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTagsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTagsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTagsInner(val *ResourceTagsInner) *NullableResourceTagsInner {
	return &NullableResourceTagsInner{value: val, isSet: true}
}

func (v NullableResourceTagsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTagsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


