/*
Hava

Hava API

API version: 1.1.2
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// ViewResourcesInner struct for ViewResourcesInner
type ViewResourcesInner struct {
	// The unique ID of the resource
	Id *string `json:"id,omitempty"`
}

// NewViewResourcesInner instantiates a new ViewResourcesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewResourcesInner() *ViewResourcesInner {
	this := ViewResourcesInner{}
	return &this
}

// NewViewResourcesInnerWithDefaults instantiates a new ViewResourcesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewResourcesInnerWithDefaults() *ViewResourcesInner {
	this := ViewResourcesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ViewResourcesInner) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewResourcesInner) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ViewResourcesInner) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ViewResourcesInner) SetId(v string) {
	o.Id = &v
}

func (o ViewResourcesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableViewResourcesInner struct {
	value *ViewResourcesInner
	isSet bool
}

func (v NullableViewResourcesInner) Get() *ViewResourcesInner {
	return v.value
}

func (v *NullableViewResourcesInner) Set(val *ViewResourcesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViewResourcesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViewResourcesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewResourcesInner(val *ViewResourcesInner) *NullableViewResourcesInner {
	return &NullableViewResourcesInner{value: val, isSet: true}
}

func (v NullableViewResourcesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewResourcesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


