/*
Hava

Hava API

API version: 1.1.2
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// JobsShow200Response struct for JobsShow200Response
type JobsShow200Response struct {
	// The unique ID of the job
	Id *string `json:"id,omitempty"`
	// The state of the job
	State *string `json:"state,omitempty"`
}

// NewJobsShow200Response instantiates a new JobsShow200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsShow200Response() *JobsShow200Response {
	this := JobsShow200Response{}
	return &this
}

// NewJobsShow200ResponseWithDefaults instantiates a new JobsShow200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsShow200ResponseWithDefaults() *JobsShow200Response {
	this := JobsShow200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *JobsShow200Response) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsShow200Response) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *JobsShow200Response) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *JobsShow200Response) SetId(v string) {
	o.Id = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *JobsShow200Response) GetState() string {
	if o == nil || isNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsShow200Response) GetStateOk() (*string, bool) {
	if o == nil || isNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *JobsShow200Response) HasState() bool {
	if o != nil && !isNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *JobsShow200Response) SetState(v string) {
	o.State = &v
}

func (o JobsShow200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.State) {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableJobsShow200Response struct {
	value *JobsShow200Response
	isSet bool
}

func (v NullableJobsShow200Response) Get() *JobsShow200Response {
	return v.value
}

func (v *NullableJobsShow200Response) Set(val *JobsShow200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsShow200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsShow200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsShow200Response(val *JobsShow200Response) *NullableJobsShow200Response {
	return &NullableJobsShow200Response{value: val, isSet: true}
}

func (v NullableJobsShow200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsShow200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


