/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// ResourceConnections struct for ResourceConnections
type ResourceConnections struct {
	// The unique ID of the connection
	Id *string `json:"id,omitempty"`
	// The unique ID of the resource this connection is from
	ResourceId *string `json:"resource_id,omitempty"`
	// The unique ID of the resource this connection is to
	RemoteResourceId *string `json:"remote_resource_id,omitempty"`
	// The type of the resource this connection is to
	RemoteResourceType *string `json:"remote_resource_type,omitempty"`
	// Additional data related to this connection
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewResourceConnections instantiates a new ResourceConnections object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceConnections() *ResourceConnections {
	this := ResourceConnections{}
	return &this
}

// NewResourceConnectionsWithDefaults instantiates a new ResourceConnections object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceConnectionsWithDefaults() *ResourceConnections {
	this := ResourceConnections{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResourceConnections) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConnections) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResourceConnections) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ResourceConnections) SetId(v string) {
	o.Id = &v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise.
func (o *ResourceConnections) GetResourceId() string {
	if o == nil || isNil(o.ResourceId) {
		var ret string
		return ret
	}
	return *o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConnections) GetResourceIdOk() (*string, bool) {
	if o == nil || isNil(o.ResourceId) {
		return nil, false
	}
	return o.ResourceId, true
}

// HasResourceId returns a boolean if a field has been set.
func (o *ResourceConnections) HasResourceId() bool {
	if o != nil && !isNil(o.ResourceId) {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given string and assigns it to the ResourceId field.
func (o *ResourceConnections) SetResourceId(v string) {
	o.ResourceId = &v
}

// GetRemoteResourceId returns the RemoteResourceId field value if set, zero value otherwise.
func (o *ResourceConnections) GetRemoteResourceId() string {
	if o == nil || isNil(o.RemoteResourceId) {
		var ret string
		return ret
	}
	return *o.RemoteResourceId
}

// GetRemoteResourceIdOk returns a tuple with the RemoteResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConnections) GetRemoteResourceIdOk() (*string, bool) {
	if o == nil || isNil(o.RemoteResourceId) {
		return nil, false
	}
	return o.RemoteResourceId, true
}

// HasRemoteResourceId returns a boolean if a field has been set.
func (o *ResourceConnections) HasRemoteResourceId() bool {
	if o != nil && !isNil(o.RemoteResourceId) {
		return true
	}

	return false
}

// SetRemoteResourceId gets a reference to the given string and assigns it to the RemoteResourceId field.
func (o *ResourceConnections) SetRemoteResourceId(v string) {
	o.RemoteResourceId = &v
}

// GetRemoteResourceType returns the RemoteResourceType field value if set, zero value otherwise.
func (o *ResourceConnections) GetRemoteResourceType() string {
	if o == nil || isNil(o.RemoteResourceType) {
		var ret string
		return ret
	}
	return *o.RemoteResourceType
}

// GetRemoteResourceTypeOk returns a tuple with the RemoteResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConnections) GetRemoteResourceTypeOk() (*string, bool) {
	if o == nil || isNil(o.RemoteResourceType) {
		return nil, false
	}
	return o.RemoteResourceType, true
}

// HasRemoteResourceType returns a boolean if a field has been set.
func (o *ResourceConnections) HasRemoteResourceType() bool {
	if o != nil && !isNil(o.RemoteResourceType) {
		return true
	}

	return false
}

// SetRemoteResourceType gets a reference to the given string and assigns it to the RemoteResourceType field.
func (o *ResourceConnections) SetRemoteResourceType(v string) {
	o.RemoteResourceType = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResourceConnections) GetData() map[string]interface{} {
	if o == nil || isNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConnections) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResourceConnections) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *ResourceConnections) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o ResourceConnections) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.ResourceId) {
		toSerialize["resource_id"] = o.ResourceId
	}
	if !isNil(o.RemoteResourceId) {
		toSerialize["remote_resource_id"] = o.RemoteResourceId
	}
	if !isNil(o.RemoteResourceType) {
		toSerialize["remote_resource_type"] = o.RemoteResourceType
	}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableResourceConnections struct {
	value *ResourceConnections
	isSet bool
}

func (v NullableResourceConnections) Get() *ResourceConnections {
	return v.value
}

func (v *NullableResourceConnections) Set(val *ResourceConnections) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceConnections) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceConnections) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceConnections(val *ResourceConnections) *NullableResourceConnections {
	return &NullableResourceConnections{value: val, isSet: true}
}

func (v NullableResourceConnections) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceConnections) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


