/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// EnvironmentsenvironmentIdsharesConfig Configuration for the generated view. Only used for PNG
type EnvironmentsenvironmentIdsharesConfig struct {
	// Display connections on the exported diagram
	Connections *bool `json:"connections,omitempty"`
	// Display diagram in isometric view
	Isometric *bool `json:"isometric,omitempty"`
	// Display labels such as names on the diagram
	Labels *bool `json:"labels,omitempty"`
}

// NewEnvironmentsenvironmentIdsharesConfig instantiates a new EnvironmentsenvironmentIdsharesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentsenvironmentIdsharesConfig() *EnvironmentsenvironmentIdsharesConfig {
	this := EnvironmentsenvironmentIdsharesConfig{}
	return &this
}

// NewEnvironmentsenvironmentIdsharesConfigWithDefaults instantiates a new EnvironmentsenvironmentIdsharesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentsenvironmentIdsharesConfigWithDefaults() *EnvironmentsenvironmentIdsharesConfig {
	this := EnvironmentsenvironmentIdsharesConfig{}
	return &this
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *EnvironmentsenvironmentIdsharesConfig) GetConnections() bool {
	if o == nil || isNil(o.Connections) {
		var ret bool
		return ret
	}
	return *o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsenvironmentIdsharesConfig) GetConnectionsOk() (*bool, bool) {
	if o == nil || isNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *EnvironmentsenvironmentIdsharesConfig) HasConnections() bool {
	if o != nil && !isNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given bool and assigns it to the Connections field.
func (o *EnvironmentsenvironmentIdsharesConfig) SetConnections(v bool) {
	o.Connections = &v
}

// GetIsometric returns the Isometric field value if set, zero value otherwise.
func (o *EnvironmentsenvironmentIdsharesConfig) GetIsometric() bool {
	if o == nil || isNil(o.Isometric) {
		var ret bool
		return ret
	}
	return *o.Isometric
}

// GetIsometricOk returns a tuple with the Isometric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsenvironmentIdsharesConfig) GetIsometricOk() (*bool, bool) {
	if o == nil || isNil(o.Isometric) {
		return nil, false
	}
	return o.Isometric, true
}

// HasIsometric returns a boolean if a field has been set.
func (o *EnvironmentsenvironmentIdsharesConfig) HasIsometric() bool {
	if o != nil && !isNil(o.Isometric) {
		return true
	}

	return false
}

// SetIsometric gets a reference to the given bool and assigns it to the Isometric field.
func (o *EnvironmentsenvironmentIdsharesConfig) SetIsometric(v bool) {
	o.Isometric = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *EnvironmentsenvironmentIdsharesConfig) GetLabels() bool {
	if o == nil || isNil(o.Labels) {
		var ret bool
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsenvironmentIdsharesConfig) GetLabelsOk() (*bool, bool) {
	if o == nil || isNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *EnvironmentsenvironmentIdsharesConfig) HasLabels() bool {
	if o != nil && !isNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given bool and assigns it to the Labels field.
func (o *EnvironmentsenvironmentIdsharesConfig) SetLabels(v bool) {
	o.Labels = &v
}

func (o EnvironmentsenvironmentIdsharesConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !isNil(o.Isometric) {
		toSerialize["isometric"] = o.Isometric
	}
	if !isNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentsenvironmentIdsharesConfig struct {
	value *EnvironmentsenvironmentIdsharesConfig
	isSet bool
}

func (v NullableEnvironmentsenvironmentIdsharesConfig) Get() *EnvironmentsenvironmentIdsharesConfig {
	return v.value
}

func (v *NullableEnvironmentsenvironmentIdsharesConfig) Set(val *EnvironmentsenvironmentIdsharesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentsenvironmentIdsharesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentsenvironmentIdsharesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentsenvironmentIdsharesConfig(val *EnvironmentsenvironmentIdsharesConfig) *NullableEnvironmentsenvironmentIdsharesConfig {
	return &NullableEnvironmentsenvironmentIdsharesConfig{value: val, isSet: true}
}

func (v NullableEnvironmentsenvironmentIdsharesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentsenvironmentIdsharesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


