/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// ViewIdExportBody struct for ViewIdExportBody
type ViewIdExportBody struct {
	// The format to export the view to
	ExportFormat *string `json:"export_format,omitempty"`
	// Display connections on the exported diagram
	Connections *bool `json:"connections,omitempty"`
	// Display diagram in isometric view
	Isometric *bool `json:"isometric,omitempty"`
	// Display labels such as names on the diagram
	Labels *bool `json:"labels,omitempty"`
	// The ID of the view revision to export (optional)
	RevisionId *string `json:"revision_id,omitempty"`
}

// NewViewIdExportBody instantiates a new ViewIdExportBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewIdExportBody() *ViewIdExportBody {
	this := ViewIdExportBody{}
	return &this
}

// NewViewIdExportBodyWithDefaults instantiates a new ViewIdExportBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewIdExportBodyWithDefaults() *ViewIdExportBody {
	this := ViewIdExportBody{}
	return &this
}

// GetExportFormat returns the ExportFormat field value if set, zero value otherwise.
func (o *ViewIdExportBody) GetExportFormat() string {
	if o == nil || isNil(o.ExportFormat) {
		var ret string
		return ret
	}
	return *o.ExportFormat
}

// GetExportFormatOk returns a tuple with the ExportFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewIdExportBody) GetExportFormatOk() (*string, bool) {
	if o == nil || isNil(o.ExportFormat) {
		return nil, false
	}
	return o.ExportFormat, true
}

// HasExportFormat returns a boolean if a field has been set.
func (o *ViewIdExportBody) HasExportFormat() bool {
	if o != nil && !isNil(o.ExportFormat) {
		return true
	}

	return false
}

// SetExportFormat gets a reference to the given string and assigns it to the ExportFormat field.
func (o *ViewIdExportBody) SetExportFormat(v string) {
	o.ExportFormat = &v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *ViewIdExportBody) GetConnections() bool {
	if o == nil || isNil(o.Connections) {
		var ret bool
		return ret
	}
	return *o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewIdExportBody) GetConnectionsOk() (*bool, bool) {
	if o == nil || isNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *ViewIdExportBody) HasConnections() bool {
	if o != nil && !isNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given bool and assigns it to the Connections field.
func (o *ViewIdExportBody) SetConnections(v bool) {
	o.Connections = &v
}

// GetIsometric returns the Isometric field value if set, zero value otherwise.
func (o *ViewIdExportBody) GetIsometric() bool {
	if o == nil || isNil(o.Isometric) {
		var ret bool
		return ret
	}
	return *o.Isometric
}

// GetIsometricOk returns a tuple with the Isometric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewIdExportBody) GetIsometricOk() (*bool, bool) {
	if o == nil || isNil(o.Isometric) {
		return nil, false
	}
	return o.Isometric, true
}

// HasIsometric returns a boolean if a field has been set.
func (o *ViewIdExportBody) HasIsometric() bool {
	if o != nil && !isNil(o.Isometric) {
		return true
	}

	return false
}

// SetIsometric gets a reference to the given bool and assigns it to the Isometric field.
func (o *ViewIdExportBody) SetIsometric(v bool) {
	o.Isometric = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ViewIdExportBody) GetLabels() bool {
	if o == nil || isNil(o.Labels) {
		var ret bool
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewIdExportBody) GetLabelsOk() (*bool, bool) {
	if o == nil || isNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ViewIdExportBody) HasLabels() bool {
	if o != nil && !isNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given bool and assigns it to the Labels field.
func (o *ViewIdExportBody) SetLabels(v bool) {
	o.Labels = &v
}

// GetRevisionId returns the RevisionId field value if set, zero value otherwise.
func (o *ViewIdExportBody) GetRevisionId() string {
	if o == nil || isNil(o.RevisionId) {
		var ret string
		return ret
	}
	return *o.RevisionId
}

// GetRevisionIdOk returns a tuple with the RevisionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewIdExportBody) GetRevisionIdOk() (*string, bool) {
	if o == nil || isNil(o.RevisionId) {
		return nil, false
	}
	return o.RevisionId, true
}

// HasRevisionId returns a boolean if a field has been set.
func (o *ViewIdExportBody) HasRevisionId() bool {
	if o != nil && !isNil(o.RevisionId) {
		return true
	}

	return false
}

// SetRevisionId gets a reference to the given string and assigns it to the RevisionId field.
func (o *ViewIdExportBody) SetRevisionId(v string) {
	o.RevisionId = &v
}

func (o ViewIdExportBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ExportFormat) {
		toSerialize["export_format"] = o.ExportFormat
	}
	if !isNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !isNil(o.Isometric) {
		toSerialize["isometric"] = o.Isometric
	}
	if !isNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !isNil(o.RevisionId) {
		toSerialize["revision_id"] = o.RevisionId
	}
	return json.Marshal(toSerialize)
}

type NullableViewIdExportBody struct {
	value *ViewIdExportBody
	isSet bool
}

func (v NullableViewIdExportBody) Get() *ViewIdExportBody {
	return v.value
}

func (v *NullableViewIdExportBody) Set(val *ViewIdExportBody) {
	v.value = val
	v.isSet = true
}

func (v NullableViewIdExportBody) IsSet() bool {
	return v.isSet
}

func (v *NullableViewIdExportBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewIdExportBody(val *ViewIdExportBody) *NullableViewIdExportBody {
	return &NullableViewIdExportBody{value: val, isSet: true}
}

func (v NullableViewIdExportBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewIdExportBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


