/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// AccountIdTokensBody struct for AccountIdTokensBody
type AccountIdTokensBody struct {
	// The name of the token to create
	Name *string `json:"name,omitempty"`
}

// NewAccountIdTokensBody instantiates a new AccountIdTokensBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountIdTokensBody() *AccountIdTokensBody {
	this := AccountIdTokensBody{}
	return &this
}

// NewAccountIdTokensBodyWithDefaults instantiates a new AccountIdTokensBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountIdTokensBodyWithDefaults() *AccountIdTokensBody {
	this := AccountIdTokensBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AccountIdTokensBody) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountIdTokensBody) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AccountIdTokensBody) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AccountIdTokensBody) SetName(v string) {
	o.Name = &v
}

func (o AccountIdTokensBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableAccountIdTokensBody struct {
	value *AccountIdTokensBody
	isSet bool
}

func (v NullableAccountIdTokensBody) Get() *AccountIdTokensBody {
	return v.value
}

func (v *NullableAccountIdTokensBody) Set(val *AccountIdTokensBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountIdTokensBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountIdTokensBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountIdTokensBody(val *AccountIdTokensBody) *NullableAccountIdTokensBody {
	return &NullableAccountIdTokensBody{value: val, isSet: true}
}

func (v NullableAccountIdTokensBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountIdTokensBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


