/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// SharesShareIdBody struct for SharesShareIdBody
type SharesShareIdBody struct {
	Config *EnvironmentsenvironmentIdsharesConfig `json:"config,omitempty"`
}

// NewSharesShareIdBody instantiates a new SharesShareIdBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharesShareIdBody() *SharesShareIdBody {
	this := SharesShareIdBody{}
	return &this
}

// NewSharesShareIdBodyWithDefaults instantiates a new SharesShareIdBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharesShareIdBodyWithDefaults() *SharesShareIdBody {
	this := SharesShareIdBody{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *SharesShareIdBody) GetConfig() EnvironmentsenvironmentIdsharesConfig {
	if o == nil || isNil(o.Config) {
		var ret EnvironmentsenvironmentIdsharesConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharesShareIdBody) GetConfigOk() (*EnvironmentsenvironmentIdsharesConfig, bool) {
	if o == nil || isNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *SharesShareIdBody) HasConfig() bool {
	if o != nil && !isNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given EnvironmentsenvironmentIdsharesConfig and assigns it to the Config field.
func (o *SharesShareIdBody) SetConfig(v EnvironmentsenvironmentIdsharesConfig) {
	o.Config = &v
}

func (o SharesShareIdBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableSharesShareIdBody struct {
	value *SharesShareIdBody
	isSet bool
}

func (v NullableSharesShareIdBody) Get() *SharesShareIdBody {
	return v.value
}

func (v *NullableSharesShareIdBody) Set(val *SharesShareIdBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSharesShareIdBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSharesShareIdBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharesShareIdBody(val *SharesShareIdBody) *NullableSharesShareIdBody {
	return &NullableSharesShareIdBody{value: val, isSet: true}
}

func (v NullableSharesShareIdBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharesShareIdBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


