/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// AccountIdProjectsBody struct for AccountIdProjectsBody
type AccountIdProjectsBody struct {
	// The name of the project to create
	Name *string `json:"name,omitempty"`
	// A description of the project
	Description *string `json:"description,omitempty"`
}

// NewAccountIdProjectsBody instantiates a new AccountIdProjectsBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountIdProjectsBody() *AccountIdProjectsBody {
	this := AccountIdProjectsBody{}
	return &this
}

// NewAccountIdProjectsBodyWithDefaults instantiates a new AccountIdProjectsBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountIdProjectsBodyWithDefaults() *AccountIdProjectsBody {
	this := AccountIdProjectsBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AccountIdProjectsBody) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountIdProjectsBody) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AccountIdProjectsBody) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AccountIdProjectsBody) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AccountIdProjectsBody) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountIdProjectsBody) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AccountIdProjectsBody) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AccountIdProjectsBody) SetDescription(v string) {
	o.Description = &v
}

func (o AccountIdProjectsBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableAccountIdProjectsBody struct {
	value *AccountIdProjectsBody
	isSet bool
}

func (v NullableAccountIdProjectsBody) Get() *AccountIdProjectsBody {
	return v.value
}

func (v *NullableAccountIdProjectsBody) Set(val *AccountIdProjectsBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountIdProjectsBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountIdProjectsBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountIdProjectsBody(val *AccountIdProjectsBody) *NullableAccountIdProjectsBody {
	return &NullableAccountIdProjectsBody{value: val, isSet: true}
}

func (v NullableAccountIdProjectsBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountIdProjectsBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


