/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// TeamsTeamIdBody struct for TeamsTeamIdBody
type TeamsTeamIdBody struct {
	// The updated name for the team
	Name *string `json:"name,omitempty"`
	// The updated roles to assign the users in this team
	Roles []string `json:"roles,omitempty"`
}

// NewTeamsTeamIdBody instantiates a new TeamsTeamIdBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamsTeamIdBody() *TeamsTeamIdBody {
	this := TeamsTeamIdBody{}
	return &this
}

// NewTeamsTeamIdBodyWithDefaults instantiates a new TeamsTeamIdBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamsTeamIdBodyWithDefaults() *TeamsTeamIdBody {
	this := TeamsTeamIdBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TeamsTeamIdBody) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamsTeamIdBody) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TeamsTeamIdBody) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TeamsTeamIdBody) SetName(v string) {
	o.Name = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *TeamsTeamIdBody) GetRoles() []string {
	if o == nil || isNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamsTeamIdBody) GetRolesOk() ([]string, bool) {
	if o == nil || isNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *TeamsTeamIdBody) HasRoles() bool {
	if o != nil && !isNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *TeamsTeamIdBody) SetRoles(v []string) {
	o.Roles = v
}

func (o TeamsTeamIdBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	return json.Marshal(toSerialize)
}

type NullableTeamsTeamIdBody struct {
	value *TeamsTeamIdBody
	isSet bool
}

func (v NullableTeamsTeamIdBody) Get() *TeamsTeamIdBody {
	return v.value
}

func (v *NullableTeamsTeamIdBody) Set(val *TeamsTeamIdBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamsTeamIdBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamsTeamIdBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamsTeamIdBody(val *TeamsTeamIdBody) *NullableTeamsTeamIdBody {
	return &NullableTeamsTeamIdBody{value: val, isSet: true}
}

func (v NullableTeamsTeamIdBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamsTeamIdBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


