/*
Hava

Hava API

API version: 1.1.1
Contact: support@hava.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package havaclient

import (
	"encoding/json"
)

// EnvironmentCurrentRevision Information about the current version of this environment
type EnvironmentCurrentRevision struct {
	// The unique ID of the current version of this environment
	Id *string `json:"id,omitempty"`
}

// NewEnvironmentCurrentRevision instantiates a new EnvironmentCurrentRevision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentCurrentRevision() *EnvironmentCurrentRevision {
	this := EnvironmentCurrentRevision{}
	return &this
}

// NewEnvironmentCurrentRevisionWithDefaults instantiates a new EnvironmentCurrentRevision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentCurrentRevisionWithDefaults() *EnvironmentCurrentRevision {
	this := EnvironmentCurrentRevision{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EnvironmentCurrentRevision) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentCurrentRevision) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EnvironmentCurrentRevision) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EnvironmentCurrentRevision) SetId(v string) {
	o.Id = &v
}

func (o EnvironmentCurrentRevision) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentCurrentRevision struct {
	value *EnvironmentCurrentRevision
	isSet bool
}

func (v NullableEnvironmentCurrentRevision) Get() *EnvironmentCurrentRevision {
	return v.value
}

func (v *NullableEnvironmentCurrentRevision) Set(val *EnvironmentCurrentRevision) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentCurrentRevision) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentCurrentRevision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentCurrentRevision(val *EnvironmentCurrentRevision) *NullableEnvironmentCurrentRevision {
	return &NullableEnvironmentCurrentRevision{value: val, isSet: true}
}

func (v NullableEnvironmentCurrentRevision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentCurrentRevision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


