/*
Hava

Testing ReportsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_ReportsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ReportsApiService ReportsIndex", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ReportsApi.ReportsIndex(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ReportsApiService ReportsReportIdExportPost", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var reportId string

        resp, httpRes, err := apiClient.ReportsApi.ReportsReportIdExportPost(context.Background(), reportId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ReportsApiService ReportsShow", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var reportId string

        resp, httpRes, err := apiClient.ReportsApi.ReportsShow(context.Background(), reportId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
