/*
Hava

Testing APITokensApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_APITokensApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test APITokensApiService ApiTokensCreate", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var accountId string

        resp, httpRes, err := apiClient.APITokensApi.ApiTokensCreate(context.Background(), accountId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test APITokensApiService ApiTokensDelete", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var accountId string
        var tokenId string

        resp, httpRes, err := apiClient.APITokensApi.ApiTokensDelete(context.Background(), accountId, tokenId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test APITokensApiService ApiTokensIndex", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var accountId string

        resp, httpRes, err := apiClient.APITokensApi.ApiTokensIndex(context.Background(), accountId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
